apiVersion: v1
kind: ConfigMap
metadata:
  name: rad-guard-dynamic-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-guard
    app_version: {{ .Values.ksocGuard.image.tag | quote }}
    maintained_by: ksoc
data:
# Placeholder for dynamic configuration created via ksoc-sync
# Main purpose of this ConfigMap is to delete it when ksoc-plugins helm chart is uninstalled
