{{- if and .Values.ksocNodeAgent .Values.ksocNodeAgent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksoc-node-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
  {{- with .Values.ksocNodeAgent.serviceAccountAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ksoc-node-agent-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [ "rad-runtime-dynamic-configuration", "rad-runtime-exporter-dynamic-configuration" ]
    verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: Secret
metadata:
  name: ksoc-node-agent-api-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
  annotations:
    kubernetes.io/service-account.name: ksoc-node-agent
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ksoc-node-agent
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets", "jobs", "cronjobs"]
    verbs: ["get", "watch", "list"]

  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "watch", "list"]

  - apiGroups: [""]
    resources: ["configmaps", "pods", "nodes", "services"]
    verbs: ["get", "watch", "list" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksoc-node-agent
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  kind: ClusterRole
  name: ksoc-node-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ksoc-node-agent
    namespace: {{ .Release.Namespace }}

---

{{- if ( eq .Values.eksAddon.enabled false ) }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-now-agent-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-node-agent
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-node-agent
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-node-agent-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-node-agent-configmap-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-node-agent
    namespace: {{ .Release.Namespace }}

---


{{- end }}
{{- end }}
