{{- if .Values.ksocSync.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksoc-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-sync
    app_version: {{ .Values.ksocSync.image.tag | quote }}
    maintained_by: ksoc
spec:
  minReadySeconds: 90
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app_name: ksoc-sync
  template:
    metadata:
      labels:
        app_name: ksoc-sync
        app_version: {{ .Values.ksocSync.image.tag | quote }}
        maintained_by: ksoc
      annotations:
        {{- if .Values.workloads.disableServiceMesh }}
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
        {{- end }}
        {{- with .Values.ksocSync.podAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: ksoc-sync
      {{- if .Values.workloads.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.workloads.imagePullSecretName }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      initContainers:
{{ include "ksoc-plugins.bootstrap-initcontainer" . | indent 8 }}
      containers:
        - name: ksoc-sync
          image: {{ .Values.ksocSync.image.repository }}:{{ .Values.ksocSync.image.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: AGENT_VERSION
              value: {{ .Values.ksocSync.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: KSOC_API_URL
              value: {{ .Values.ksoc.apiUrl }}
            - name: KSOC_NAMESPACE
              value: {{ .Release.Namespace }}
{{ include "ksoc-plugins.access-key-env-secret" . | indent 12 }}
            {{- range $key, $value := .Values.ksocSync.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: api-token
            readOnly: true
          resources:
{{ toYaml .Values.ksocSync.resources | indent 12 }}
      {{- with .Values.ksocSync.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.ksocSync.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
      volumes:
      - name: api-token
        secret:
          secretName: ksoc-sync-api-token-secret
{{- end -}}
