{{- if and .Values.k9 .Values.k9.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ksoc-k9-response
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "delete", "update"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"] ## TODO:: rahul :: watch is needed only for cm, later we can remove it.
  verbs: ["get", "list", "create", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "update", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksoc-k9-response
subjects:
- kind: ServiceAccount
  name: agent-ksoc-k9
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ksoc-k9-response
  apiGroup: rbac.authorization.k8s.io

---

{{- end -}}
