apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ksoc-kube-root-ca-reader
  namespace: kube-system
  labels:
    maintained_by: ksoc
rules:
  - apiGroups: [""]
    resources: [ "configmaps" ]
    resourceNames: [ "kube-root-ca.crt" ]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-guard-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-guard
    app_version: {{ .Values.ksocGuard.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-guard
    namespace: {{ .Release.Namespace }}

---
{{- if and .Values.k9 .Values.k9.enabled -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-k9-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-sbom
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: agent-ksoc-k9
    namespace: {{ .Release.Namespace }}

---
{{- end -}}

{{- if and .Values.ksocNodeAgent .Values.ksocNodeAgent.enabled -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-now-agent-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-node-agent
    app_version: {{ .Values.ksocNodeAgent.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-node-agent
    namespace: {{ .Release.Namespace }}

---
{{- end -}}

{{- if .Values.ksocSbom.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-sbom-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-sbom
    app_version: {{ .Values.ksocSbom.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-sbom
    namespace: {{ .Release.Namespace }}
---
{{- end -}}

{{- if .Values.ksocSync.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-sync-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-sync
    app_version: {{ .Values.ksocSync.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-sync
    namespace: {{ .Release.Namespace }}
---
{{- end -}}

{{- if .Values.ksocWatch.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-watch-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-watch
    namespace: {{ .Release.Namespace }}
{{- end -}}
