apiVersion: v2
name: ksoc-plugins
version: 1.4.22
description: A Helm chart to run the KSOC plugins
home: https://ksoc.com
icon: https://ksoc.com/hubfs/Ksoc-logo.svg
keywords:
  - kubernetes
  - helm
  - opa
  - ksoc
maintainers:
  - name: KSOC Engineering
    email: engineering@ksoc.com
annotations:
  artifacthub.io/category: security
  # Possible kind options are added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |
    - kind: changed
      description: Moved RBAC resources that were created in kube-system namespace to a seperate file
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/ksoclabs/ksoc-plugins-helm-chart
    - name: support
      url: https://github.com/ksoclabs/ksoc-plugins-helm-chart/issues
