{{- if .Values.ksocWatch.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksoc-watch
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
spec:
  minReadySeconds: 90
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app_name: ksoc-watch
  template:
    metadata:
      labels:
        app_name: ksoc-watch
        app_version: {{ .Values.ksocWatch.image.tag | quote }}
        maintained_by: ksoc
      annotations:
        {{- if .Values.workloads.disableServiceMesh }}
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
        {{- end }}
        {{- with .Values.ksocWatch.podAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      serviceAccountName: ksoc-watch
      {{- if .Values.workloads.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.workloads.imagePullSecretName }}
      {{- end }}
      initContainers:
{{ include "ksoc-plugins.bootstrap-initcontainer" . | indent 8 }}
      containers:
        - name: ksoc-watch
          image: {{ .Values.ksocWatch.image.repository }}:{{ .Values.ksocWatch.image.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: AGENT_VERSION
              value: {{ .Values.ksocWatch.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: KSOC_API_URL
              value: {{ .Values.ksoc.apiUrl }}
            - name: KSOC_NAMESPACE
              value: {{ .Release.Namespace }}
{{ include "ksoc-plugins.access-key-env-secret" . | indent 12 }}
            {{- if .Values.ksocWatch.ingestCustomResources }}
            - name: INGEST_CUSTOM_RESOURCES
              value: "true"
            - name: CUSTOM_RESOURCE_RULES_PATH
              value: /var/run/custom-resource-rules/rules.yaml
            {{- end }}
            {{- range $key, $value := .Values.ksocWatch.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: api-token
            readOnly: true
          {{- if .Values.ksocWatch.ingestCustomResources }}
          - mountPath: /var/run/custom-resource-rules
            name: custom-resource-rules
            readOnly: true
          {{- end }}
          resources:
{{ toYaml .Values.ksocWatch.resources | indent 12 }}
      {{- with .Values.ksocWatch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.ksocWatch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
      volumes:
      - name: api-token
        secret:
          secretName: ksoc-watch-api-token-secret
      {{- if .Values.ksocWatch.ingestCustomResources }}
      - name: custom-resource-rules
        configMap:
          name: ksoc-watch-custom-resource-rules
      {{- end }}
{{- end -}}
