{{- if .Values.ksocWatch.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksoc-watch
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: ksoc-watch-api-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
  annotations:
    kubernetes.io/service-account.name: ksoc-watch
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ksoc-watch-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [ "ksoc-watch-dynamic-configuration" ]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ksoc-watch
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods", "services", "serviceaccounts"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [ "apps" ]
    resources: [ "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "batch" ]
    resources: [ "cronjobs", "jobs"]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterrolebindings", "clusterroles", "rolebindings", "roles" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "ksoc.com" ]
    resources: [ "guardpolicies", "guardresults" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses", "networkpolicies" ]
    verbs: [ "get", "list", "watch" ]

  {{- if .Values.ksocWatch.ingestCustomResources }}
  {{ range .Values.ksocWatch.customResourceRules.allowlist }}
  - apiGroups: {{ .apiGroups | toJson }}
    resources: {{ .resources | toJson }}
    verbs: [ "get", "list", "watch" ]
  {{ end }}
  {{- end }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-watch-configmap-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-watch-configmap-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-watch
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksoc-watch
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ksoc-watch
subjects:
  - kind: ServiceAccount
    name: ksoc-watch
    namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-watch-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-watch
    app_version: {{ .Values.ksocWatch.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-watch
    namespace: {{ .Release.Namespace }}
{{- end -}}
