{{- if .Values.ksocRuntime.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksoc-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
spec:
  replicas: {{ .Values.ksocRuntime.reporter.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app_name: ksoc-runtime
  template:
    metadata:
      labels:
        app_name: ksoc-runtime
        app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
        maintained_by: ksoc
      annotations:
        {{- if .Values.workloads.disableServiceMesh }}
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
        {{- end }}
        {{- with .Values.ksocRuntime.podAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: ksoc-runtime
      {{- if .Values.workloads.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.workloads.imagePullSecretName }}
      {{- end }}
      automountServiceAccountToken: false
      initContainers:
{{ include "ksoc-plugins.bootstrap-initcontainer" . | indent 8 }}
      {{- if and .Values.priorityClass.enabled .Values.priorityClass.name }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      containers:
        - name: ksoc-runtime
          image: {{ .Values.ksocRuntime.reporter.image.repository }}:{{ .Values.ksocRuntime.reporter.image.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          {{- if .Values.ksoc.seccompProfile.enabled }}
            seccompProfile:
              type: RuntimeDefault
          {{- end }}
          env:
            - name: AGENT_VERSION
              value: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: KSOC_API_URL
              value: {{ .Values.ksoc.apiUrl }}
            - name: KSOC_NAMESPACE
              value: {{ .Release.Namespace }}
{{ include "ksoc-plugins.access-key-env-secret" . | indent 12 }}
            {{- range $key, $value := .Values.ksocRuntime.reporter.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          ports:
          - containerPort: 8000
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: api-token
            readOnly: true
          resources:
{{ toYaml .Values.ksocRuntime.reporter.resources | indent 12 }}
      {{- with .Values.ksocRuntime.reporter.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.ksocRuntime.reporter.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: api-token
          secret:
            defaultMode: 420
            secretName: ksoc-runtime-api-token-secret
{{- end -}}
