{{- if .Values.ksocRuntime.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksoc-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: ksoc-runtime-api-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
  annotations:
    kubernetes.io/service-account.name: ksoc-runtime
type: kubernetes.io/service-account-token

---

{{ if ( eq .Values.eksAddon.enabled false ) -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksoc-runtime-kube-root-ca-reader
  namespace: kube-system
  labels:
    app_name: ksoc-runtime
    app_version: {{ .Values.ksocRuntime.reporter.image.tag | quote }}
    maintained_by: ksoc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksoc-kube-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: ksoc-runtime
    namespace: {{ .Release.Namespace }}

---

{{- end }}
{{- end }}
